### ISSUE TITLE
 library not found for -lstorm-pomdp

### ISSUE THREAD

**Issue by zzhou63** [moves-rwth/stormpy#189]
When I went to the step: python3 setup.py develop, I faced this issue:
[100%] Linking CXX shared module /Users/chikako/VeriPlan/stormpy/lib/stormpy/pomdp/pomdp.cpython-311-darwin.so
ld: library not found for -lstorm-pomdp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/chikako/VeriPlan/stormpy/lib/stormpy/pomdp/pomdp.cpython-311-darwin.so] Error 1
make[2]: *** [CMakeFiles/pomdp.dir/all] Error 2
make[1]: *** [CMakeFiles/pomdp.dir/rule] Error 2
make: *** [pomdp] Error 2
Traceback (most recent call last):
  File "/Users/chikako/VeriPlan/stormpy/setup.py", line 192, in <module>
    setup(
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/command/develop.py", line 35, in run
    self.install_for_development()
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/command/develop.py", line 112, in install_for_development
    self.run_command('build_ext')
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/Users/chikako/VeriPlan/stormpy/setup.py", line 162, in run
    subprocess.check_call(['cmake', '--build', '.', '--target', ext.name] + build_args, cwd=self.build_temp)
  File "/Users/chikako/miniconda3/envs/rag/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'pomdp', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.

**Comment by zzhou63** [comment]
I solved this:
1. find where is libstorm-pomdp
2. run the command, just add the path by ourselves:
 export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
 export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
3. re-run : python3 setup.py develop, and it works
